
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.18.0
 * Query Engine version: 34b5a692b7bd79939a9a2c3ef97d816e749cda2f
 */
Prisma.prismaVersion = {
  client: "6.18.0",
  engine: "34b5a692b7bd79939a9a2c3ef97d816e749cda2f"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  fullname: 'fullname',
  email: 'email',
  username: 'username',
  role: 'role',
  profile_image: 'profile_image',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  organization: 'organization',
  organization_short_code: 'organization_short_code',
  contact_person: 'contact_person',
  contact_person_email: 'contact_person_email',
  username: 'username',
  profile_image: 'profile_image',
  role: 'role',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  abbreviation: 'abbreviation',
  type: 'type',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AttendeesScalarFieldEnum = {
  id: 'id',
  prefix: 'prefix',
  fullname: 'fullname',
  email: 'email',
  phone_number: 'phone_number',
  nin: 'nin',
  nin_verified: 'nin_verified',
  position: 'position',
  grade: 'grade',
  organization: 'organization',
  department: 'department',
  department_agency: 'department_agency',
  staff_id: 'staff_id',
  office_location: 'office_location',
  remark: 'remark',
  status: 'status',
  role: 'role',
  password: 'password',
  temporal_password: 'temporal_password',
  registeredAt: 'registeredAt',
  created_by_id: 'created_by_id',
  created_by_type: 'created_by_type',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BoothsScalarFieldEnum = {
  id: 'id',
  booth_number: 'booth_number',
  location: 'location',
  price: 'price',
  booth_size: 'booth_size',
  features: 'features',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ExhibitorsScalarFieldEnum = {
  id: 'id',
  prefix: 'prefix',
  company_name: 'company_name',
  contact_person: 'contact_person',
  contact_email: 'contact_email',
  contact_phone: 'contact_phone',
  website: 'website',
  description: 'description',
  service_product_to_exhibit: 'service_product_to_exhibit',
  password: 'password',
  role: 'role',
  status: 'status',
  registeredAt: 'registeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventPartnersScalarFieldEnum = {
  id: 'id',
  prefix: 'prefix',
  fullname: 'fullname',
  email: 'email',
  phone_number: 'phone_number',
  company_name: 'company_name',
  logo: 'logo',
  website: 'website',
  social_media: 'social_media',
  description: 'description',
  why_interested: 'why_interested',
  password: 'password',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SpeakersScalarFieldEnum = {
  id: 'id',
  prefix: 'prefix',
  first_name: 'first_name',
  last_name: 'last_name',
  fullname: 'fullname',
  country: 'country',
  job_title: 'job_title',
  organization: 'organization',
  phone: 'phone',
  social_media: 'social_media',
  work_email: 'work_email',
  bio: 'bio',
  topic: 'topic',
  experience: 'experience',
  password: 'password',
  role: 'role',
  status: 'status',
  registeredAt: 'registeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventPackagesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  features: 'features',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SpeakerPackageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  price: 'price',
  description: 'description',
  features: 'features',
  limitedText: 'limitedText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PartnerPackageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  price: 'price',
  description: 'description',
  features: 'features',
  limitedText: 'limitedText',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Assigned_boothsScalarFieldEnum = {
  id: 'id',
  booth_id: 'booth_id',
  assigned_to_id: 'assigned_to_id',
  assignedAt: 'assignedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EventPartnerPackagesScalarFieldEnum = {
  id: 'id',
  event_partner_id: 'event_partner_id',
  event_package_id: 'event_package_id',
  payment_reference: 'payment_reference',
  payment_status: 'payment_status',
  payment_method: 'payment_method',
  proof_of_payment: 'proof_of_payment',
  assignedAt: 'assignedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  super_admin: 'super_admin',
  attendee: 'attendee',
  ministry: 'ministry',
  agency: 'agency',
  parastatal: 'parastatal',
  exhibitor: 'exhibitor',
  public_speaker: 'public_speaker',
  event_partner: 'event_partner',
  other: 'other'
};

exports.OrganizationType = exports.$Enums.OrganizationType = {
  MINISTRY: 'MINISTRY',
  AGENCY: 'AGENCY',
  PARASTATAL: 'PARASTATAL',
  OTHER: 'OTHER'
};

exports.Status = exports.$Enums.Status = {
  Approved: 'Approved',
  Pending: 'Pending',
  Rejected: 'Rejected',
  Available: 'Available',
  SoldOut: 'SoldOut',
  Reserved: 'Reserved',
  Paid: 'Paid'
};

exports.CreatorType = exports.$Enums.CreatorType = {
  ADMIN: 'ADMIN',
  USER: 'USER'
};

exports.Prisma.ModelName = {
  Admin: 'Admin',
  Users: 'Users',
  Organization: 'Organization',
  Attendees: 'Attendees',
  Booths: 'Booths',
  Exhibitors: 'Exhibitors',
  EventPartners: 'EventPartners',
  Speakers: 'Speakers',
  EventPackages: 'EventPackages',
  SpeakerPackage: 'SpeakerPackage',
  PartnerPackage: 'PartnerPackage',
  assigned_booths: 'assigned_booths',
  EventPartnerPackages: 'EventPartnerPackages'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
